name: Generic Collections
author: nicbell
category: Native
tags: [collections, generics]
#source: http://github.com/nicbell/MooCollections/Source
#demo: http://github.com/nicbell/MooCollections/Demo
#current: v0.75